id: P000757
initial_creation_type: ocr
source_metadata:
  id: bdr:W7503
  title: རྩིས་ཀྱི་བསྟན་བཅོས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  volumes:
    2a5178280df143e2b1281b7231070cd2:
      image_group_id: I01CT1761
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
