id: P000757
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:01:24.034942
source_metadata:
  id: bdr:W7503
  title: རྩིས་ཀྱི་བསྟན་བཅོས་རིན་ཆེན་གཏེར་མཛོད
  author: ''
  volumes:
    2a5178280df143e2b1281b7231070cd2:
      image_group_id: I01CT1761
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
