id: I3662D27C
legacy_id: P000757
ocr_import_info:
  bdrc_scan_id: W7503
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T14:13:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:15:10.449984+00:00'
last_modified: 2022-09-04 11:15:34.072955
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W7503
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW7503
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩིས་ཀྱི་བསྟན་བཅོས་རིན་ཆེན་གཏེར་མཛོད།
  author: དཔའ་བོ ༠༢་གཙུག་ལག་འཕྲེང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.5114911761668696
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I01CT1761:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01CT1761
      total_pages: 420
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01CT1761.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.5114911761668696
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
